version: '3.9'
services:
  frontend_headhunter:
    container_name: 'frontend_headhunter'
    build: .
    command: yarn start
    ports:
      - 3001:3001
    volumes:
      - ./:/app/
      - /app/node_modules